### ISSUE TITLE
Set `text/plain;charset=UTF-8` when content-type is missing.

### ISSUE THREAD

**Issue by yusukebe** [honojs/node-server#100]

**Comment by yusukebe** [comment]
This is fixed in #95

**Comment by marbemac** [comment]
Hi @yusukebe - what was the rationale here (at least for streaming responses)? 

This causes the browser to render plain text when streaming back html (while when not set the browser is correctly able to figure out that the stream is html). Could of course manually set the content-type header to html, but this isn't always possible (for example, the remix server runtime handler doesn't expose an option to do so and doesn't set the content-type header itself).

**Comment by yusukebe** [comment]
Hi @marbemac 

I'd like to know the specific code example of the problem.

This issue means that applications should always add `content-type`, and when it is not present, the runtime or server will add `text/plain`.
