### ISSUE TITLE
Unable to use zValidator for query with POST requests

### ISSUE THREAD

**Issue by kolyasapphire** [honojs/node-server#113]
Hey! First of all thank you so much for your Hono and the Node.js adapter work - they are awesome!

I've noticed that this code works fine with just Hono on Vercel inside Next.js:

```ts
import { Hono } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { handle } from 'hono/vercel'
import * as z from 'zod'

const schema = z.object({
  test: z.string(),
})

const app = new Hono().post('*', zValidator('query', schema), (c) =>
  c.text('test')
)

export default handle(app)

export const runtime = 'edge'
```

But when using the `honojs/node-server` like so:

```ts
import { Hono } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { handle } from '@hono/node-server/vercel'
import * as z from 'zod'

const schema = z.object({
  test: z.string(),
})

const app = new Hono().post('*', zValidator('query', schema), (c) =>
  c.text('test')
)

export default handle(app)
```

I am getting:

```console
TypeError: Response body object should not be disturbed or locked
at extractBody (node:internal/deps/undici/undici:5178:17)
at new Request (node:internal/deps/undici/undici:6160:48)
at newRequestFromIncoming (file:///hono-tests/node_modules/@hono/node-server/dist/vercel.mjs:160:10)
at [getRequestCache] (file:///hono-tests/node_modules/@hono/node-server/dist/vercel.mjs:173:35)
at Request.get (file:///hono-tests/node_modules/@hono/node-server/dist/vercel.mjs:192:35)
at HonoRequest.header (file:///hono-tests/node_modules/hono/dist/request.js:73:23)
at /hono-tests/node_modules/hono/dist/cjs/validator/validator.js:29:31
at dispatch (file:///hono-tests/node_modules/hono/dist/compose.js:29:23)
at file:///hono-tests/node_modules/hono/dist/compose.js:6:12
at file:///hono-tests/node_modules/hono/dist/hono-base.js:247:31
at Hono.dispatch (file:///hono-tests/node_modules/hono/dist/hono-base.js:257:7)
at fetch (file:///hono-tests/node_modules/hono/dist/hono-base.js:59:19)
at file:///hono-tests/node_modules/@hono/node-server/dist/vercel.mjs:275:13
at /hono-tests/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
at /hono-tests/node_modules/next/dist/server/lib/trace/tracer.js:133:36
```

Without `zValidator` it also works as expected.

**Comment by yusukebe** [comment]
Hi @kolyasapphire,

I've tried running the code, but it seems to work fine on my environment. Therefore, the issue might be related to package dependencies. Could you create a GitHub project to reproduce the issue? Once you do that, I can investigate it.

**Comment by kolyasapphire** [comment]
Hey @yusukebe,

Absolutely, here you go:
https://codesandbox.io/p/devbox/angry-voice-26yy73

<img width="1354" alt="Screenshot 2023-12-16 at 21 38 15" src="https://github.com/honojs/node-server/assets/4752441/7bb1421c-e535-46d2-8247-212cb3369d7f">

Thanks for looking into this!

**Comment by yusukebe** [comment]
@kolyasapphire 

Thanks! You might fix this issue with adding the following:

```ts
export const config = {
  api: {
    bodyParser: false
  }
}
```

This is related to https://github.com/honojs/node-server/issues/84

**Comment by herrAlison** [comment]
import requests


with requests.session() as session:

 url = 'https://register.fdsinstitut.com/ext/index.php'

 headers = {}
 cookies = {}
 donnees = {} 

 reponse = session.post(url, headers=headers, cookies=cookies, data=donnees)

 print(reponse.text)

**Comment by herrAlison** [comment]
dieses programm löuft nicht richtig ,

**Comment by kolyasapphire** [comment]
Thanks @yusukebe! Works as expected now
