### ISSUE TITLE
Error: The response is not an instance of Response, but [object Object]

### ISSUE THREAD

**Issue by lorefnon** [honojs/node-server#116]
In https://github.com/honojs/node-server/pull/115, an explicit `instanceof Response` check was added. This breaks for libraries/integrations that use the [@whatwg-node/events](https://www.npmjs.com/package/@whatwg-node/events) ponyfill package. A prominent example is graphql-yoga which can no longer be used with hono & node-server because the response returned is an instance of [PonyfillResponse](https://github.com/ardatan/whatwg-node/blob/00a0dd315e4afd927870980ebbb574e6cda2f208/packages/node-fetch/src/Response.ts#L15) that does not pass the `instanceof Response` check.

Reverting to 1.3.3 resolves the problem.

**Comment by yusukebe** [comment]
@lorefnon 

This is an issue that needs to be resolved immediately. Thanks for the report.

**Comment by yusukebe** [comment]
Hi @lorefnon 

This issue should be fixed in the latest version `v1.3.5`. Please try it out.
