### ISSUE TITLE
Return 400 or 500 if the Host header contains a path.

### ISSUE THREAD

**Issue by usualoma** [honojs/node-server#161]
Currently, the path is passed directly to the URL if it is included in the host header, but should return 400.

app
```
const app = new Hono()
app.get('/', (c) => c.text(c.req.url))
```

request
```
$ curl http://localhost:3002 -H 'Host: localhsot/?key=value'
http://localhsot/?key=value/
```

### How does it behave on other servers?

`bun` and `deno` have the same result as the current `node-server`.
`wrangler dev` results in a 500 error

**Comment by yusukebe** [comment]
This was closed by #163. Thanks!
