### ISSUE TITLE
Bug: Unable to use Hono in Nextjs 14 App Dir with nodejs runtime

### ISSUE THREAD

**Issue by MathurAditya724** [honojs/node-server#174]
Unable to use hono in nextjs app dir with nodejs runtime

Example Code
```ts
// app/api/[[...route]]/route.ts
import { Hono } from 'hono'
import { handle } from '@hono/node-server/vercel'

const app = new Hono().basePath('/api')

app.get('/hello', async (c) => {
    return c.json({
        message: 'Hello Next.js!',
    })
})

export const GET = handle(app)
```

Error - 
![image](https://github.com/honojs/node-server/assets/57684218/e9e0f79b-54b3-4e05-9a15-ef4ee5613172)

This code has been recreated from the docs https://hono.dev/getting-started/vercel#node-js for the app dir. It works if we set the runtime to `edge` and use the `hono/vercel` package like this -
```ts
import { Hono } from 'hono'
import { handle } from 'hono/vercel'

export const runtime = "edge"

const app = new Hono().basePath('/api')

app.get('/hello', async (c) => {
    return c.json({
        message: 'Hello Next.js!',
    })
})

export const GET = handle(app)
```

**Comment by Axibord** [comment]
I have the same bug trying to run Hono (large application setup) with Next.js (App router) using Node.js runtime

You don't have to specify `export const runtime = "edge"` for it to work on Vercel tho.

I think the bug comes from the original `request` `response` being modified by Next.js

**Comment by firstian** [comment]
I can't run on edge for the reason of having to do native connection to Postgres (complained about pg-native needing fs). I was able to use the nodejs runtime with App Router (deploying to Vercel). The difference is I import handle from hono/vercel instead.

**Comment by MathurAditya724** [comment]
Interesting, yes it is working. We should update the docs.

**Comment by MathurAditya724** [comment]
On another thought, what's the purpose of the `@hono/node-server/vercel` file? Only for the pages dir?

**Comment by firstian** [comment]
Where is the documentation for this runtime setting? I can see docs to the RuntimeKey, but that looks somewhat different than this. I only found out how this works by setting it to something else and look through the error messages.

**Comment by joseavr** [comment]
It's here: https://hono.dev/docs/getting-started/vercel#node-js

The hono.dev documentation is kinda vague. It doesn't explcity explain what each line does.

For example, the constant `config: pageConfig` is not being used and also it comes from Next.js, which also they dont have any documentation on this. TBH I dont know what this constant is for.

Anyone know how to setup so that I can use node.js runtime in my Next.js 14? (actually 15 since is stable now), I will highly appreciate it.

**Comment by paulwongx** [comment]
Yeah the documentation is confusing. 

1) Is it required to use `edge` runtime with this `import { handle } from 'hono/vercel'`? 
- In my local dev, it works without setting runtime to edge 
2) Is this required to run in nodejs runtime? `import { handle } from '@hono/node-server/vercel'`
- My app errors if I try to use that
3) As questioned above, what scenarios is this needed for? App directory? Pages directory? Edge? Node?
- 
```ts
export const config: PageConfig = {
  api: {
    bodyParser: false,
  },
}
```

**Comment by paulwongx** [comment]
> > Where is the documentation for this runtime setting?
> 
> @firstian It's here: https://hono.dev/docs/getting-started/vercel#node-js
> 
> The hono.dev documentation is kinda vague. It doesn't explicitly explain what each line does.
> 
> For example, the constant `config: pageConfig` is not being used and also it comes from Next.js, which also they dont have any documentation on this. TBH I dont know what this constant is for.
> 
> Anyone know how to setup so that I can use node.js runtime in my Next.js 14? (actually 15 since is stable now), I will highly appreciate it.

See my comment above for the solution. It should work with `import { handle } from 'hono/vercel'`

**Comment by rafaell-lycan** [comment]
@yusukebe how can we add these details to the docs?

**Comment by yusukebe** [comment]
@rafaell-lycan 

Is this good for you? https://github.com/honojs/website/pull/528

**Comment by MathurAditya724** [comment]
Yes, this provides much-needed clarity on the issue discussed here.

**Comment by yusukebe** [comment]
Okay! Shall we close this issue?
