### ISSUE TITLE
Read default port from env

### ISSUE THREAD

**Issue by schettn** [honojs/node-server#196]
Hi!

I want to deploy a Hono app with node on Heroku.

To achieve this I need to set the port manually by reading the env.

```ts
serve(
  {
    fetch: app.fetch,
    port: process.env.PORT ? parseInt(process.env.PORT) : 3000,
  },
  (info) => {
    console.log(`Server running on http://${info.address}:${info.port}`);
  }
);
```

Instead I want to avoid this manual configuration in favour of `@hono/node-server` reading the `process.env.PORT` by default. Why is this not the default behaviour?

**Comment by yusukebe** [comment]
@schettn 

Hmmm. It may not be a `@hono/node-server` matter. Can you try it outside the `serve` function?

**Comment by schettn** [comment]
Sorry I don't understand. What do you mean with `outside` the `serve`?

**Comment by schettn** [comment]
> It may not be a @hono/node-server matter.

Do you mean the node-server already supports this or that it is out of scope?

**Comment by yusukebe** [comment]
Sorry, I misunderstood. How it treats the process.env.port is out of the scope of this Node.js adapter.

**Comment by schettn** [comment]
Okay. I initially asked this question because when you use Hono with bun you have this behaviour.

For example:

```ts
import {Hono} from "hono"

const app = new Hono()

Bun.serve(app)
```

`PORT=4000 bun run ./app.ts` starts the server on the correct port.


Now when you switch to node:
```ts
import {Hono} from "hono"
import {serve} from '@hono/node-server'


const app = new Hono()

serve(app)
```

`PORT=4000 bun run ./app.ts` starts the server on port `3000` instead of `4000`.

**Comment by yusukebe** [comment]
@schettn 

That's the difference between starting with Bun's API and starting with a Node.js adapter. It's not related to our implementation.

**Comment by schettn** [comment]
Any chance that you could support this nevertheless?

It would be beneficial for me because I have a startup process that then runs the app `pylon dev -c 'node ./pylon/index.js`.
I would like to support a `--port `parameter in `pylon dev` without the need to configure this on "user land".

ref: https://pylon-docs.vercel.app/docs/release-notes/migrating-from-v1-to-v2#update-your-start-script

**Comment by schettn** [comment]
> @schettn
> 
> That's the difference between starting with Bun's API and starting with a Node.js adapter. It's not related to our implementation.

Yes I understand. Just asking.

**Comment by yusukebe** [comment]
> Any chance that you could support this nevertheless?

No. Although `process.env.PORT` may be commonly used, it is not specified in documents. The Node.js adapter should be general and not too opinionated.

**Comment by schettn** [comment]
Ok, no big deal. Thanks for you time!
