### ISSUE TITLE
HTTP2 server example from documentation does not work

### ISSUE THREAD

**Issue by cahilfoley** [honojs/node-server#214]
I was implementing the example from the Hono main documentation on implementing HTTP2 with Node.js [here](https://hono.dev/docs/getting-started/nodejs#http2) and encountered malformed responses from the server.

I have created a minimal reproduction based on the example from the documentation. This codesandbox starts both a standard HTTP1.X server and a HTTP2 server with the same Hono app to demonstrate that it works with the standard `node:http` package but not `node:http2` as referenced in the docs - [CodeSandbox Link](https://codesandbox.io/p/devbox/hono-http2-test-rhsgxh).

Hopefully I've just done something wrong because I'd love to get HTTP2 working in this new project I'm working on, thanks for all the hard work!

**Comment by yusukebe** [comment]
HI @cahilfoley 

Accoding to [the Node.js document](https://nodejs.org/api/http2.html#http2createsecureserveroptions-onrequesthandler):

> The following illustrates a simple HTTP/2 server using the Core API. Since there are no browsers known that support [unencrypted HTTP/2](https://http2.github.io/faq/#does-http2-require-encryption), the use of [http2.createSecureServer()](https://nodejs.org/api/http2.html#http2createsecureserveroptions-onrequesthandler) is necessary when communicating with browser clients.

So, please use `createSecureServer`:
https://hono.dev/docs/getting-started/nodejs#encrypted-http2

**Comment by cahilfoley** [comment]
That will do it, thanks!

**Comment by yusukebe** [comment]
@cahilfoley Good! Closing.
