### ISSUE TITLE
Is the behavior of getConnInfo as expected ?

### ISSUE THREAD

**Issue by shogo-kurokawa-nm** [honojs/node-server#215]
In the current implementation, the remote.address field is set with the value obtained from `const address = bindings.incoming.socket.address() as AddressInfo`. However, this method, `socket.address()`, retrieves the server's socket address rather than the remote client’s address.

https://github.com/honojs/node-server/blob/350f9b7fba008e26231771e3d82087250e6c9561/src/conninfo.ts#L13

This raises two potential issues:

Field Name and Value Mismatch
The field remote.address typically implies it would contain the address of the remote client (i.e., the origin of the connection). Using `socket.address()` may lead to misunderstandings, as it actually refers to the server’s address.

Expected Address Information
If the goal is to store the remote client's address, we may need to use something like `socket.remoteAddress` instead, which would reflect the client's IP.

Background:

I noticed this issue while using Hono’s [ipRestriction](https://hono.dev/docs/middleware/builtin/ip-restriction) middleware in a Node.js environment. The documentation suggested using ipRestriction(getConnInfo, {}), but it didn’t work as expected.

If getConnInfo itself is behaving as intended, then there may be a need to adjust the ipRestriction middleware to align with expected functionality.

I haven’t tested this in other runtimes, but they might have the same issue.

Apologies if I misunderstood the intended behavior.

**Comment by yusukebe** [comment]
@shogo-kurokawa-nm Thank you for the issue.

Hi @nakasyou, can you take look at this?

**Comment by nakasyou** [comment]
Sorry, that's my mistake. It should be fixed.

**Comment by nakasyou** [comment]
Hi @shogo-kurokawa-nm, could review this?

**Comment by shogo-kurokawa-nm** [comment]
@nakasyou Thank you for fixing the issue. LGTM
