### ISSUE TITLE
Client premature close (abort) not detected

### ISSUE THREAD

**Issue by Tomas2D** [honojs/node-server#217]
Detection of client's premature close has been fixed by https://github.com/honojs/node-server/issues/107, but lately broken again via https://github.com/honojs/node-server/commit/ba26b944572d2c92551fd9aeac1349a335f3b3f5.

**Comment by usualoma** [comment]
Hi @Tomas2D
Thank you for creating the issue.

We are aware that the current node-server may not detect connection disconnections in some cases. However, as mentioned in https://github.com/honojs/node-server/pull/172, `incoming.destroyed` also becomes true for a normal POST request, so we are not using it in the node server.

It would be good if we could detect that the connection was really aborted, excluding the case of a normal POST request.

**Comment by Tomas2D** [comment]
I see. But based on https://github.com/nodejs/node/issues/46666 we could do this instead.

```
      outgoing.on('close', () => {
        if (incoming.errored) {
          req[getAbortController]().abort(incoming.errored.toString())
        } else if (!outgoing.writableFinished) {
          req[getAbortController]().abort('Client connection prematurely closed.')
        }
      })
```

**Comment by usualoma** [comment]
@Tomas2D Thanks for the reply!
I've confirmed that using `outgoing.writableFinished` does indeed give the expected result.

Could you please update https://github.com/honojs/node-server/pull/218 with this information? We would also appreciate it if you could add a test. If adding a test is difficult, we can handle it here.

**Comment by Tomas2D** [comment]
Great. PR has been updated. I updated tests also to cover non-GET HTTP requests.

**Comment by yusukebe** [comment]
@Tomas2D 

Can we close this issue now?

**Comment by Tomas2D** [comment]
Sure. Thank you.
