### ISSUE TITLE
Serve Static

### ISSUE THREAD

**Issue by yusukebe** [honojs/node-server#3]
We have to implement `serveStatic` function like a [Serve Static Middleware](https://honojs.dev/docs/builtin-middleware/serve-static/).

```ts
import { server, serveStatic } from '@honojs/node-server'
```

**Comment by that-ambuj** [comment]
I have been able to create a serve static middleware with readFileSync, but I'm unable to set Content-Type headers from the middleware. Hence, Unable to display content correctly. I have forked this repo and made changes with an example to show.
my repo: https://github.com/that-ambuj/hono-node-server
please check the example directory and run
```ts
yarn
yarn dev:example
```

**Comment by yusukebe** [comment]
Hi @that-ambuj !

Your repository is the same as this repository. Did you forget "push"?

**Comment by that-ambuj** [comment]
Sorry, I forgot to mention in the url, It's in serveStatic Branch.
https://github.com/that-ambuj/hono-node-server/tree/serveStatic

This should work now.

**Comment by that-ambuj** [comment]
Hey @yusukebe! 
I have been able to able to make the middleware work by changing `c.headers('Content-Type',mimeType)` to `c.res.headers.set('Content-Type', mimeType)` in my middleware.
Will me commiting to main and opening a PR!

**Comment by yusukebe** [comment]
This issue is closed. Thank you @that-ambuj !
