### ISSUE TITLE
Feature requrest: node 18 native stream and fetch support

### ISSUE THREAD

**Issue by tangye1234** [honojs/node-server#35]
This project use remix-run/web-std-io as the underlying mechanism to support web standard.

While nodejs 18+ has already support that well, I think we should polyfill those implementations.
Pr will be made soon

**Comment by yusukebe** [comment]
Hi @tangye1234 !

Yes, it's grate to use Web Standard API in Node.js 18+. But, we previously tried an implementation using Node.js 18+ Web Standard, but it was slow, so we decided to use Remix's.

Though, now with newer versions of Node.js, performance may be improved. Also, It may be more important to keep the file size small than to make it larger and faster.

Either way, I would like to benchmark using the simple implementation with Node.js 18+ Web Standard.

**Comment by tangye1234** [comment]
I recently did some benchmarks, which have revealed that the native implementation of nodejs 18 still falls short in terms of performance when compared to the `web-stream-polyfill`.

Nevertheless, I can offer an alternative polyfill to those people who truely desire native node fetch and stream support.
> Notice: this require node 18+

First you need to `npm install require-in-the-middle`

In your project, add a polyfill.ts with following codes
```typescript
import { Hook } from 'require-in-the-middle'
import { resolve } from 'path'

class NodeRequest extends Request {
  constructor(input: RequestInfo, init?: RequestInit) {
    super(input, {
      ...init,
      ...(init?.body instanceof ReadableStream ? { duplex: 'half' } : {}),
    })
  }
}

Object.defineProperty(NodeRequest.constructor, 'name', { value: 'Request' })

new Hook(
  [resolve('./node_modules/@hono/node-server/dist/globals.js')],
  (exports, _name, _basedir) => {
    if (
      exports instanceof Object &&
      'installGlobals' in exports &&
      typeof exports.installGlobals === 'function'
    ) {
      return {
        ...exports,
        installGlobals: () => {
          global.Request = NodeRequest as any
        },
      }
    }
    return exports as any
  }
)

```

Then import your polyfil before using @hono/node-server.
You are ready to play with nodejs' native fetch and web stream.

**Comment by sebastianwessel** [comment]
Thanks for sharing @tangye1234 

I agree, that supporting node below 18 is an important point and it is good and requires polyfills.

But, to get an idea of the performance, I did some short test - so I simply share it for everybody.  

It's not a real stable test with multiple runs and different payload sizes and so on.  
But it's ok to get some idea, I guess.

I created a striped-down version of node-serve, where I...

- replaced the `"@remix-run/web-stream": "^1.0.3"` in favor of `node:stream/web`
- removed `atob`, `btoa`, `Blob`, `FormData` and so on.  

The handler code:

```typescript
app.get('/one', async (c) => {
  let body = 'one'

  for (let index = 0; index < 1000; index++) {
    body += ' one'
  }
  return c.text(body)
})
```

Than, I ran simply `autocannon http://127.0.0.1:8081/one --renderStatusCodes` on Node 18.5

```
Running 10s test @ http://127.0.0.1:8081/one
10 connections
```

## Native web stream

### Node 18.5

| Stat    | 2.5% | 50%  | 97.5% | 99%  | Avg     | Stdev   | Max   |
|---|---|---|---|---|---|---|---|
| Latency | 0 ms | 0 ms | 1 ms  | 1 ms | 0.06 ms | 0.27 ms | 16 ms |

| Stat      | 1%      | 2.5%    | 50%     | 97.5%   | Avg      | Stdev   | Min     |
|---        |---      |---      |---      |---      |---       |---      |---      |
| Req/Sec   | 16527   | 16527   | 19247   | 19647   | 19002.91 | 826.58  | 16525   |
| Bytes/Sec | 68.9 MB | 68.9 MB | 80.2 MB | 81.9 MB | 79.2 MB  | 3.45 MB | 68.9 MB |

| Code | Count  |
|--|--|
| 200  | 209035 |

### Node 20.0

| Stat    | 2.5% | 50%  | 97.5% | 99%  | Avg     | Stdev   | Max   |
|---|---|---|---|---|---|---|---|
| Latency | 0 ms | 0 ms | 1 ms  | 1 ms | 0.05 ms | 0.28 ms | 17 ms |

| Stat      | 1%      | 2.5%    | 50%     | 97.5%   | Avg      | Stdev   | Min     |
|---        |---      |---      |---      |---      |---       |---      |---      |
| Req/Sec   | 17215   | 17215   | 19599   | 19903   | 19366.55 | 711.78  | 17203   |
| Bytes/Sec | 71.8 MB | 71.8 MB | 81.7 MB | 83 MB | 80.7 MB  | 2.97 MB | 71.7 MB |

| Code | Count  |
|--|--|
| 200  | 213012 |

## Original `node-server`

### Node 18.5

| Stat    | 2.5% | 50%  | 97.5% | 99%  | Avg     | Stdev   | Max   |
|---|---|---|---|---|---|---|---|
| Latency | 0 ms | 0 ms | 0 ms  | 0 ms | 0.02 ms  | 0.14 ms | 14 ms |

| Stat      | 1%      | 2.5%    | 50%     | 97.5%   | Avg      | Stdev   | Min     |
|---        |---      |---      |---      |---      |---       |---      |---      |
| Req/Sec   | 23247   | 23247   | 25791   | 26255   | 25534.4 | 822.67   | 23244   |
| Bytes/Sec | 96.9 MB  | 96.9 MB | 107 MB | 109 MB | 106 MB  | 3.42 MB | 96.9 MB |

| Code | Count  |
|--|--|
| 200  | 255337 |

### Node 20.0

| Stat    | 2.5% | 50%  | 97.5% | 99%  | Avg     | Stdev   | Max   |
|---|---|---|---|---|---|---|---|
| Latency | 0 ms | 0 ms | 0 ms  | 0 ms | 0.02 ms  | 0.14 ms | 14 ms |

| Stat      | 1%      | 2.5%    | 50%     | 97.5%   | Avg      | Stdev   | Min     |
|---        |---      |---      |---      |---      |---       |---      |---      |
| Req/Sec   | 25215   | 25215   | 25663   | 25983   | 25615.28 |  262.32   | 25200   |
| Bytes/Sec | 105 MB  | 105 MB | 107 MB | 108 MB | 107 MB  | 1.09 MB | 105 MB |

| Code | Count  |
|--|--|
| 200  | 281756 |

**Comment by yusukebe** [comment]
Hi @tangye1234, @sebastianwessel!

Thanks for sharing the interesting findings.

I'm reevaluating whether we should use `@remix-run/*` or the native web APIs available in Node.js 18+. According to the benchmarks provided by @sebastianwessel, the app using native web APIs is slower. However, I now want to utilize the native web APIs and remove the polyfill associated with `@remix-run/*`.

Originally, Hono did not support Node.js, and only utilized web standard APIs. Therefore, we wouldn't expect to need polyfills for external libraries such as `@remix-run/*` if Node.js supports web standard APIs natively. It's best to use them. The main concern is "performance," especially whether it's fast enough. However, it is faster than Express, which remains a popular framework in the Node.js world despite the existence of Fastify. This makes it worth considering for production use.

There are advantages to using native APIs. The resulting application will be significantly smaller than the current version. It will also offer better compatibility, ensuring features like `CompressionStream` work well. Additionally, it is likely to become faster with future updates.

<img width="871" alt="SS" src="https://user-images.githubusercontent.com/10682/235049566-126708ab-89f3-417b-b0f0-38121578054b.png">

It's a difficult decision, but for Node.js, I believe that being extremely fast is not as crucial. Thus, opting to use only native APIs could be a better choice. Moreover, we don't need to support Node.js versions lower than 16, even though it could work with polyfills. It's important to keep the project focused.

What are your thoughts on this matter?

**Comment by sebastianwessel** [comment]
Hey @yusukebe 

I can only speak for myself.
I prefer the "cleaner" and smaller version. Reasons for it:

- node-server is already kind of polyfill
- less code and fewer dependencies = less maintenance
- smaller code size helps to reduce costs (money & resources) and it is important on edge/IoT envs
- raw throughput is less important these days, because if you reach such limits, you should scale in most cases
- could-startup time is more important (serverless & co) and smaller code should be faster here or?

And also very important - the speed of the server itself might be high, higher or super ultra-high.
But in real world, the handlers are slowing down all the stuff. They do computations, database access and so on.
So, if you save 0.1ms or not per request does not really matter.

If it matters for some use cases, then you should go for Bun anyways 😜

I switched/decided to go for Hono for my framework, because it's well maintained, small, clean, handy/familiar to use, and because it supports the usage of native benefits of different runtimes like Bun.
Also, custom extensions like a router, is straight forward and done in minutes. 
The raw throughput was not really part of the decision.

The only reasons I would not go for the native solution would be to support older Node versions or if the Node native thing is buggy.

Think it is no waste of time to refactor to native and then do proper performance testing and then do the final go/no-go.

**Comment by yusukebe** [comment]
Thanks. I would also like to know @tangye1234's opinion.

**Comment by renhiyama** [comment]
I'm also gonna vote for using native node APIs when available. 18kb size seems way better. The performance seems reasonable, and one can switch to other runtime or wait for nodejs to improve their performance.

**Comment by tangye1234** [comment]
Hello @yusukebe, please accept my apologies for the delayed response.

IMHO, it appears that `@hono/node-server` is designed to facilitate native nodejs support. If concerns regarding performance or old version node arise, I suggest using polyfills as an alternative. This will greatly reduce maintenance efforts.

I've already submitted a native refactor pull request on https://github.com/honojs/node-server/pull/40. However, I believe it requires further review or at the very least, should be published as a canary.

**Comment by renhiyama** [comment]
If that's the case, maybe dynamically import dependency (polyfills) if the native API is not available. Make use of "optional dependency" feature in npm, and not bundle it straight away with the main package. Notify in hono node server docs to install those optional dependencies if one's using older node version. And/or even throw an error if the node version is old + optional dependency not installed. This brings the best of both worlds hopefully! Same for performance based polyfills, load them if they're available. Make use of dynamic imports!

**Comment by yusukebe** [comment]
Thanks a lot! 

Then, basically, let's go with using the Node.js 18+ native Web Standard API!

I'll check PR #40.

**Comment by tangye1234** [comment]
The related PR #41 is merged into `next` branch.

**Comment by yusukebe** [comment]
@tangye1234 Thank you!

I'll release it such as `v1.0.0-rc.1` or a canary version later.

**Comment by yusukebe** [comment]
Hi forks! I've released `1.0.0-rc.1` with Node +18 native web standard API support.

Try:

```
yarn add @hono/node-server@1.0.0-rc.1
```

**Comment by renhiyama** [comment]
@yusukebe not sure but this rc version isn't showing on github releases page 😅

**Comment by yusukebe** [comment]
@renhiyama 
https://github.com/honojs/node-server/releases/tag/v1.0.0-rc.1

The reason it does not appear on the top page is because it's just a pre-release.

**Comment by yusukebe** [comment]
This was finished! Thanks!
