### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by schonert** [honojs/node-server#37]
Hey! 
I'm trying to add SSL to our dev env but can't seem to access this line in an elegant way. 
I assume that by swapping that out with the `createServer` from `node:https` would do the trick.
https://github.com/honojs/node-server/blob/68b2475e45da38e9acdd79538c7c3cd235d6488a/src/server.ts#L12

A solution could be either default to `node:https` or expose `getRequestListener` so that we can create our own `serve` with https.

What do you think?

**Comment by yusukebe** [comment]
Hi @schonert !

As you mentioned, we do need to support SSL.

> A solution could be either default to node:https or expose getRequestListener so that we can create our own serve with https.

I believe exposing the getRequestListener function is a better choice, as it enables users to select between node:http and node:https. However, I would like to refactor the names of the functions and variables before exporting them. Please bear with me for a moment.

Thanks for the good suggestion!
