### ISSUE TITLE
Document how to use Hono with Vercel & NodeJS runtime

### ISSUE THREAD

**Issue by alexiglesias93** [honojs/node-server#46]
Currently, [the docs for Vercel](https://hono.dev/getting-started/vercel) only explain how to deploy Hono on the edge runtime.
When removing the `runtime: 'edge'` config, Hono doesn't work anymore.

After some digging, I found [this PR in the node-server adapter](https://github.com/honojs/node-server/pull/23) that seems to implement exactly what I need, but with the lack of documentation I haven't been able to successfully use the adapter. I might be doing something wrong but can't find the issue.

Any help/documentation will be appreciated, thank you very much for the work you're doing.

**Comment by yusukebe** [comment]
Hi @alexiglesias93!

Thank you for creating this issue.

I'm currently working on the documentation for the next minor version, "v3.2". I'll be sure to include this information in there!

By the way, I'd love to hear about your experience using Vercel/Next.js & Node.js in your product. Please share your thoughts whenever you have the time!

**Comment by alexiglesias93** [comment]
Awesome, thank you!
Well, my current plan is to move away from a traditional hosted NodeJS server that runs an Express app to a serverless environment.
But I have a few dependencies that require a NodeJs runtime so I thought that using Vercel functions would be the best and easier approach.
My idea is to use Hono to migrate our backend to Vercel functions with their NodeJS runtime, hence why the default `vercel` adapter doesn't work because it requires using the edge runtime.

**Comment by yusukebe** [comment]
That's great!

So, if you can eliminate the Node.js dependencies from your application, you can smoothly migrate it to the Edge. You just need to remove the Node.js adapter :)

**Comment by alexiglesias93** [comment]
> That's great!
> 
> So, if you can eliminate the Node.js dependencies from your application, you can smoothly migrate it to the Edge. You just need to remove the Node.js adapter :)

Correct, that's our long-term goal.
It's not an immediate thing we can do, because we use a few libraries that require a NodeJS environment like firebase. That's why it's very handy if we can migrate to Vercel functions under the NodeJS runtime.

**Comment by yusukebe** [comment]
@alexiglesias93 

Thanks! Fixed!

**Comment by yusukebe** [comment]
This issue can be closed.
