### ISSUE TITLE
Is it possible to make the rawResponse   from Node accessible

### ISSUE THREAD

**Issue by paul1995tu** [honojs/node-server#47]
Hi, I was wondering if it is possible to make the rawResponse accessible similar to c.req.raw ?  Some API libraries require
 nodes rawRequest and rawResponse to perform OAuth.

**Comment by paul1995tu** [comment]
@yusukebe, 
thanks for the fast response. Mhh creating a new Response doesn't work. I'm trying to build a Shopify app with Hono and Node.  To perform Shopify OAuth I need the raw request and response object here is the Example: [](https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/auth/begin.md). Using the normal Hono Response Object results in a type Error inside the Shopify API. I had similar Problems with Fastify some while ago but using reply.raw  solved it.

**Comment by yusukebe** [comment]
@paul1995tu 

Ah, which Node.js version do you use? Only version 18 or higher supports `Response`  and next major version of the node server will only works on Node.js version 18+.

Then, you may use the code for Cloudflare Workers like the following.

```ts
app.get('/auth-path', (c) => {
  return shopify.auth.begin({
    shop: shopify.utils.sanitizeShop(c.req.query('shop'), true),
    callbackPath: '/auth/callback',
    isOnline: false,
    rawRequest: c.req.raw,
  })
})
```

**Comment by paul1995tu** [comment]
@yusukebe 

Currently, using v18.16.0. I am building a monolith, that's why I actually don't want to use workers for auth  but if there is no other option i maybe go and stick with it.

**Comment by yusukebe** [comment]
@paul1995tu 

You don't have to use an actual "Cloudflare Workers". Use only "API". Try to write the code above in your current Hono app built with Node.js adapter.

**Comment by yusukebe** [comment]
You might be able to use `@shopify/shopify-api/adapters/cf-worker` in your **Node.js Hono app**. However, I'm not certain about this, so I will try it later when I have some time.

**Comment by paul1995tu** [comment]
@yusukebe 

Using cf-worker worked!  Thank you for the guidance :)

**Comment by yusukebe** [comment]
Wow!!! Great!!!
