### ISSUE TITLE
`getSetCookie` is not fully supported before version 19.7

### ISSUE THREAD

**Issue by yusukebe** [honojs/node-server#51]
Currently, we use `getSetCookie` from `Headers` to parse `set-cookie` header values.

https://github.com/honojs/node-server/blob/003e6ddbd7bd34d509d605d4cea122fdf43bc9dc/src/listener.ts#L55

This works well on all our CI environments: Node 18.x, 19.x, and 20.x.

However, `getSetCookie` is not fully supported before version 19.7.

https://developer.mozilla.org/en-US/docs/Web/API/Headers/getSetCookie

Thus, it will throw an error in "18.0.0", even though the latest "18.x" does support `getSetCookie`.

We have stated that this Node.js adapter works on Node.js "18". Therefore, I believe we need to implement a cookie parsing function instead of using the native `getSetCookie()`.

The implementation could be simple, something along the lines of:

```ts
export const getSetCookieFromString = (str: string): string[] => {
  return str.split(/\s*\,\s*/)
}
```

**Comment by yusukebe** [comment]
Hi @tangye1234 !

What do you think about it?

**Comment by tangye1234** [comment]
I personally have implemented a parser compatible with all node versions before, I will port this tomorrow with a test case inside.

**Comment by tangye1234** [comment]
I have PRed here: https://github.com/honojs/node-server/pull/53.

BTW, there is no issues about getSetCookie in the latest nodejs 18, except for the earlier versions of nodejs 18.

**Comment by tangye1234** [comment]
The nodejs version should be greater than
* 18.x => 18.14.1+
* 19.x => 19.7.0+
* 20.x => 20.0.0+
