### ISSUE TITLE
Export getRequestListener to use with express

### ISSUE THREAD

**Issue by miyamonz** [honojs/node-server#55]
I want to mount a Hono router on an Express router like this:

```
const app = express();
const hono = new Hono();
app.use("/hoge", getRequestListener(hono.fetch));
```

To achieve this, I'd like you to export the getRequestListener.

**Comment by yusukebe** [comment]
Hi @miyamonz,

Thank you for ultra cool idea! I've released version "1.0.2" which includes this change.
