### ISSUE TITLE
TypeError: `res.headers.getSetCookie` is not a function

### ISSUE THREAD

**Issue by mr4x** [honojs/node-server#58]
Hi! I got following error when I tried to set cookie:
`TypeError: res.headers.getSetCookie is not a function`
It comes from `@hono/node-server/dist/listener.js:47`:
`outgoing.setHeader(k, res.headers.getSetCookie(k));`

Tested on node v18.6.0 and v20.3.0

Code:
```
import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { setCookie } from 'hono/cookie';

const app = new Hono();
app.get('/', c => {
  setCookie(c, 'token', '123');
  return c.text('Cookie set');
});

serve({ fetch: app.fetch, port: 3001 });
```

**Comment by yusukebe** [comment]
Hi @mr4x, 

The Hono node adapter does not support `v18.6.0`. If you want to use "v18.x", use `v18.14.1` or higher.

However, it should support `v20.3.0`, so it's strange that it's not working. Please check again.

**Comment by mr4x** [comment]
@yusukebe yeah, re-tested it on 18.16 and 20.3, sorry for bothering
