### ISSUE TITLE
Unable to post from axios on certain Node.js versions

### ISSUE THREAD

**Issue by Khsmty** [honojs/node-server#59]
With Node.js v20.3.0, post to `localhost:3000` by axios succeeds, but with v18.16.0, I get an error `Error: connect ECONNREFUSED ::1:3000` and cannot post successfully.
I did not get any errors from hono.
However, post requests made via testers such as Advanced REST Client seem to succeed.

---

Node.js v20.3.0 で axios を使って `localhost:3000` へ post すると成功しますが、v18.16.0 の場合は `Error: connect ECONNREFUSED ::1:3000` というエラーが発生し、正常に post することができません。
hono からはエラーは出ていませんでした。
なお、Advanced REST Client のようなテスター経由の post リクエストは成功するようです。

**Comment by yusukebe** [comment]
@Khsmty !

Thanks you. I'll investigate it.

**Comment by yusukebe** [comment]
@Khsmty 

Could you try using `127.0.0.1:3000` instead of `localhost:3000` and let me know the result?
