### ISSUE TITLE
Empty response body for all requests

### ISSUE THREAD

**Issue by mikestopcontinues** [honojs/node-server#61]
Using `@hono/node-server`, all of my response bodies are being gobbled up. 

This happens whether I'm generating a response or serving static files. All middleware is disabled. 

The correct status codes and headers are being applied. (The one exception is 'Content-Length': 0, but that happens after any code I have access to.)

If I call `app.request()`, I receive the correct response. If I use `hono/bun`, it also works.

I'm on node 18.16.1. Any idea what's causing this?

**Comment by yusukebe** [comment]
@mikestopcontinues 

Did you create the project from `create hono` command? If not so, please try it:

```
npm create hono@latest my-app
```

For this setting, it should work well.

**Comment by mikestopcontinues** [comment]
Hi @yusukebe, I just tried that, and it worked. It helped me track down the issue to the presence of `@supabase/supabase-js`. If it gets included in the bundle, Hono goes silent. When I tried `hono/bun`, I found that they're overwriting a global. This must be what's causing the issue.

Thanks for you're help. I'm going to take this up with them!
