### ISSUE TITLE
compress middleware is slow

### ISSUE THREAD

**Issue by niklasgrewe** [honojs/node-server#79]
the `compress()` middleware on node is very slow. I tested the minified version of htmx (44KB) and it takes more than 2000ms until i get a html response from the server. I use node version `v20.5.1`

**Comment by yusukebe** [comment]
@niklasgrewe 

Thanks to creating the issue. I thought this is a node-server's bug, but it might be a Compress Middleware's bug. I'll fix it later!

**Comment by yusukebe** [comment]
Fixed it in https://github.com/honojs/hono/pull/1366. I'll release the new version of Hono soon.
