### ISSUE TITLE
No File instance for body

### ISSUE THREAD

**Issue by WildEgo** [honojs/node-server#85]
Hey I was expecting the result of the "file" input's result to be an instance of "File" instead of a string, is this normal behavior? [Here's an example of it returning a string](https://github.com/WildEgo/hono-file-instance).

Regards,
Luis Bizarro.

**Comment by yusukebe** [comment]
Hi @WildEgo 

In this case, the type is `File` on the client, but what passes to the Zod validator on the server side is not a `File` type, but Hono's original `FormData` type. Therefore, the validation in Zod will fail and return 400. So, you cannot use the File type.

**Comment by WildEgo** [comment]
> Hi @WildEgo
> 
> In this case, the type is `File` on the client, but what passes to the Zod validator on the server side is not a `File` type, but Hono's original `FormData` type. Therefore, the validation in Zod will fail and return 400. So, you cannot use the File type.

Wouldn't it make sense for the buffer util to parse for "filename" and transform the content into a `File` instance since it's available on all runtimes if I ain't wrong? That way it would also make schemas cross compatible

**Comment by yusukebe** [comment]
Hi @WildEgo 

This issue may be fixed, so please upgrade Hono to latest version and try it.
