### ISSUE TITLE
Vercel build script

### ISSUE THREAD

**Issue by sarimabbas** [honojs/node-server#88]
Hello! I am following the guidance here to setup up Hono with Node / Vercel adapter https://hono.dev/getting-started/vercel#node-js 

I scaffolded the project with `create hono` to give a package.json like this:

```
{
  "name": "myapp",
  "module": "src/index.ts",
  "type": "module",
  "scripts": {
    "vercel-dev": "vercel dev",
    "deploy": "vercel"
  },
  "dependencies": {
    "hono": "^3.7.2",
  },
  "devDependencies": {
    "vercel": "^32.4.1"
  }
}

```

When running the dev script "vercel dev", it errors asking for a "build" script as well. Do you have any ideas for what to put there? thanks so much!

```
Vercel CLI 32.4.1
Error: Your `package.json` file is missing a `build` property inside the `scripts` property.
Learn More: https://vercel.link/missing-build-script
```

**Comment by yusukebe** [comment]
Hi @sarimabbas,

Could you try creating your project using the `vercel` template?

<img width="636" alt="Screenshot 2023-10-19 at 6 51 30" src="https://github.com/honojs/node-server/assets/10682/f4255d38-104b-468e-87e1-0a195cc2a31b">

Once you've created the project, install `@hono/node-server` and rewrite the `src/index.ts`:

```ts
import { Hono } from 'hono'
import { handle } from '@hono/node-server/vercel'

const app = new Hono().basePath('/api')

app.get('/', (c) => c.json({ message: 'Hello Hono!' }))

export default handle(app)
```

**Comment by sarimabbas** [comment]
Thanks so much for your response! I followed this procedure exactly: 

1. `pnpm create hono`
2. Choose Vercel template 
3. `pnpm i && pnpm i @hono/node-server`
4. Rewrite `myapp/api/index.ts` to `src/index.ts` and copy the contents from your comment 
5. Run `pnpm start`
6. Answer Vercel CLI questions, and create new project. A `vercel.json` file is generated
7. Get the error:

```
🔗  Linked to X (created .vercel)
Error: Your `package.json` file is missing a `build` property inside the `scripts` property.
Learn More: https://vercel.link/missing-build-script
```

**Comment by yusukebe** [comment]
@sarimabbas 

Ah, super sorry! The source code should be placed on `api/index.ts`, not `src/index.ts`!

And, we have to add `"type": "module"` to `package.json`.

**Comment by sarimabbas** [comment]
> @sarimabbas 
> 
> 
> 
> Ah, super sorry! The source code should be placed on `api/index.ts`, not `src/index.ts`!
> 
> 
> 
> And, we have to add `"type": "module"` to `package.json`.

Sorry for the delay! Both those changes made it work. Thank you so much!
